### ISSUE TITLE
pcaMethods not loading with missCompare library

### ISSUE THREAD

**Issue by kieroneil** [Tirgit/missCompare#1]
I was going to walk through the complete tutorial and ran into issues immediately.
`> library(missCompare)`
Error: package or namespace load failed for ‘missCompare’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘pcaMethods’
In addition: Warning message:
package ‘missCompare’ was built under R version 3.5.3 
`> cleaned <- missCompare::clean(clindata_miss,  var_removal_threshold = 0.5, ind_removal_threshold = 0.8, missingness_coding = -9)`
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘pcaMethods’
`> install.packages("pcaMethods")`
Installing package into ‘C:/Users/koneil/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘pcaMethods’ is not available (for R version 3.5.1)
`> devtools::install_github("hredestig/pcaMethods")`
Downloading GitHub repo hredestig/pcaMethods@master
Error: Could not find tools necessary to compile a package
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

I ended up downloading a lot of build tools and got the same error message and decided to abandon.  

It looks like a useful package for missing values.  I'll re-try once the pcaMethods issue has been resolved.

**Comment by Tirgit** [comment]
Hi kieroneil,

Could you try two things?

1. Not sure which R version you are using, but make sure you use R>3.5.0 (although perhaps you should upgrade to 3.6.0)
2. Can you try install pcaMethods from Bioconductor first? 
Here is how you would do it:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("pcaMethods")

see more info here: https://www.bioconductor.org/packages/release/bioc/html/pcaMethods.html

Please let me know if these worked for you!
T
