### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by sandeshregmi** [Tirgit/missCompare#3]
is there a way to fix this issue?
missCompare::MCAR(simulated$Simulated_matrix,
                   MD_pattern = metadata$MD_Pattern,
                   NA_fraction = metadata$Fraction_missingness,
                   min_PDM = 10)
27.62% of observations (with at least one missing datapoint) covered by setting min_PDM to 10
Error: Proportion of missing cells is too large in combination with the desired number of missing variables

**Comment by Tirgit** [comment]
Hi - the only way to "fix" this is to try different values for the min_PDM argument.
I suggest you run clean (with your sensible, pre-determined variable and individual thresholds) and then missCompare::get_data() on your dataset and check the outcome object called min_PDM_thresholds. Perhaps you will need to pick a lower number to retain more information. Please also study the vignette for the package for a detailed tutorial:
vignette("misscompare")
Let me know if these steps work for you!
