### ISSUE TITLE
deprecation warnings in get_data()

### ISSUE THREAD

**Issue by AnselmJeong** [Tirgit/missCompare#5]
running `missCompare::get_data()` produces the following warning message...

> The melt generic in data.table has been passed a matrix and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(na_cor). In the next version, this warning will become an error.

May be the developer have to modify the code according to the above recommendation.

Thanks.

**Comment by Tirgit** [comment]
This is now fixed in the developer version.
Submitting an update to CRAN soon.
