### ISSUE TITLE
post_imp_diag

### ISSUE THREAD

**Issue by martaddi** [Tirgit/missCompare#6]
am using the package to impute miss rainfall data from about 12 meteorological stations. So far i was successful with most steps in the tutorial with the data "pra_data.csv", however, upon trying the post imputation diagnosis i run into errors.  The errors and actual data are attached for your kind assistance. I would be glad if you help me resolve this error. The link to the raw data is attached (https://drive.google.com/file/d/11w--Fn8mK0EkaXU3j91KPqBrGjYW_4Mi/view?usp=sharing) 
the error

diag <-post_imp_diag(cleaned,imputed$mean_imputation[[1]],scale=T,n.boot = 95)
Error in t.test.default(orig_values, imp_values, alternative = "two.sided",  : 
  not enough 'y' observations
In addition: Warning messages:
1: In stats::ks.test(orig_values, imp_values, exact = TRUE) :
  cannot compute exact p-value with ties
2: In stats::ks.test(orig_values, imp_values, exact = TRUE) :
  cannot compute exact p-value with ties
3: In stats::ks.test(orig_values, imp_values, exact = TRUE) :
  cannot compute exact p-value with ties
4: In stats::ks.test(orig_values, imp_values, exact = TRUE) :
  cannot compute exact p-value with ties
5: In stats::ks.test(orig_values, imp_values, exact = TRUE) :
  cannot compute exact p-value with ties

**Comment by esaghy** [comment]
I have the same issue and can't find the solution anywhere. Have you come up with the answer?
